import {rndArrayItem} from "../utils.js";

const phrases = [
    "Believe in yourself.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only way to do great work is to love what you do.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Motivation gets you started, habit keeps you going.",
    "Your only limit is the one you set for yourself.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best way to predict the future is to create it.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "The secret of getting ahead is getting started.",
    "No one can make you feel inferior without your consent.",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it.",
    "You miss 100% of the shots you don’t take.",
    "Successful people do what unsuccessful people are not willing to do.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The more you learn, the more you earn.",
    "Action is the foundational key to all success.",
    "Inaction breeds doubt and fear. Action breeds confidence and courage.",
    "Don't wait for opportunity. Create it.",
    "The best preparation for tomorrow is doing your best today.",
    "Great things never come from comfort zones.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You can't build a reputation on what you are going to do.",
    "Positive anything is better than negative nothing.",
    "It always seems impossible until it's done.",
    "The only limit to our growth is the limitations we set for ourselves.",
    "You are never too old to set another goal or to dream a new dream.",
    "Never give up on your dreams.",
    "Think big, start small, but most of all, start.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you.",
    "The only way to achieve success is to constantly seek improvement.",
    "Success is not a destination, it's a journey.",
    "Every day is a new opportunity to change your life.",
    "The road to success is always under construction.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "Create the kind of self that you will be happy to live with all your life.",
    "Don't wait for a light to appear at the end of the tunnel, stride down there and light the bloody thing yourself.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Be yourself; everyone else is already taken.",
    "A goal without a plan is just a wish.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Successful people are not gifted, they just work hard, then succeed on purpose.",
    "Don't watch the clock; do what it does. Keep going.",
    "Believe you can and you're halfway there.",
    "Change your thoughts and you change your world.",
    "Chase your dreams, but always know the road that will lead you home again.",
    "The only way to do great work is to love what you do.",
    "Take the risk or lose the chance.",
    "With the new day comes new strength and new thoughts.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Strive for progress, not perfection.",
    "The only way to achieve success is to constantly seek improvement.",
    "Success is not a destination, it's a journey.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only limit to our growth is the limitations we set for ourselves.",
    "Chase your dreams and the universe will open doors where there were only walls.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.",
    "The journey of a thousand miles begins with one step.",
    "Every day is a chance to be better.",
    "You only live once, but if you do it right, once is enough.",
    "Happiness is not something ready made. It comes from your own actions.",
    "In a world where you can be anything, be kind.",
    "Life is not about waiting for the storm to pass, it's about learning to dance in the rain.",
    "Keep going, the best is yet to come.",
    "Keep pushing forward, you got this!",
    "Never give up, the finish line is just ahead.",
    "Keep your head up and keep moving forward.",
    "Every obstacle is just a stepping stone to success.",
    "Perseverance is the key to unlocking your full potential.",
    "Keep pushing, success is just around the corner.",
    "Keep grinding, the hard work will pay off.",
    "The only way to succeed is to keep moving forward.",
    "Never give up, keep fighting for what you believe in.",
    "Keep moving forward, never look back.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Be the change you want to see in the world.",
    "Shoot for the moon. Even if you miss, you'll land among the stars.",
    "Take the leap and build your wings on the way down.",
    "Don't be afraid to fail, be afraid not to try.",
    "Don't wait for opportunities, create them.",
    "Be the reason someone smiles today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only limit is the one you set for yourself.",
    "The best way to predict the future is to create it.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only way to make your dreams come true is to wake up.",
    "Don't let yesterday take up too much of today.",
    "Don't watch the clock; do what it does. Keep going.",
    "Chase your dreams and the universe will open doors where there were only walls.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.",
    "Life is too short to waste time on things that don't matter.",
    "The only way to achieve success is to constantly seek improvement.",
    "Success is not a destination, it's a journey.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only limit to our growth is the limitations we set for ourselves.",
    "Chase your dreams and the universe will open doors where there were only walls.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.",
    "The journey of a thousand miles begins with one step.",
    "Every day is a chance to be better.",
    "You only live once, but if you do it right, once is enough.",
    "Happiness is not something ready made. It comes from your own actions.",
    "In a world where you can be anything, be kind.",
    "Life is not about waiting for the storm to pass, it's about learning to dance in the rain.",
    "The only limit to our success is the limits we place on our own thinking.",
    "The future is created by what we do today, not tomorrow.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "The only way to make your dreams come true is to wake up.",
    "Don't wait for opportunities, create them.",
    "Be the reason someone smiles today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only limit is the one you set for yourself.",
    "The best way to predict the future is to create it.",
    "You are never too old to set another goal or to dream a new dream.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Be the change you wish to see in the world.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Happiness is not something you postpone for the future; it is something you design for the present.",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    "The only way to do great work is to love what you do.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "The secret of success is to do the common things uncommonly well.",
    "You miss 100% of the shots you don't take.",
    "Success is not final, failure is not fatal: it's the courage to continue that counts.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your only limit is the one you set for yourself.",
    "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Success is not final, failure is not fatal: it's the courage to continue that counts.",
    "Success is not about the destination, but about the journey.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not a one-time event; it is a habit.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "Success is not final, failure is not fatal: it's the courage to continue that counts.",
    "Success is not a destination, it's a journey.",
    "Success is not about the destination, but about the journey.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "Success is not a one-time event; it is a habit.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "Success is not a one-time event; it is a habit.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do."
];

export function getPhrase() {
    return rndArrayItem(phrases)
}